// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import TimerController from "./timer_controller"
application.register("timer", TimerController)

import QueueTimerController from "./queue_timer_controller"
application.register("queue-timer", QueueTimerController)

import OnlineStatusController from "./online_status_controller"
application.register("online-status", OnlineStatusController)